name: Build and Deploy to Artifact Registry

on:
  push:
    branches:
      - main  # 当推送到主分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: |
        docker build -t <region>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-bot-image:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push <region>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-bot-image:${{ github.sha }}
